#!/usr/bin/expect -f

spawn ssh root@[lindex $argv 0]
expect "password:"
send "c0ntrail123\r"
set timeout -1
expect "]#"
send "cd contrail-ansible-deployer\r"
expect "]#"
send "ansible-playbook -i inventory/ -e orchestrator=openstack playbooks/configure_instances.yml\r"
expect "]#"
send "ansible-playbook -i inventory/ playbooks/install_openstack.yml\r"
expect "]#"
send "ansible-playbook -i inventory/ -e orchestrator=openstack playbooks/install_contrail.yml\r"
expect "]#"
send "yum install -y gcc python-devel\r"
expect "]#"
send "rm -rf /usr/lib/python2.7/site-packages/ipaddress*\r"
expect "]#"
send "pip uninstall decorator\r"
expect "(y/n)?"
send "y\r"
expect "]#"
send "pip install ipaddress\r"
expect "]#"
send "pip install decorator\r"
expect "]#"
send "pip install python-openstackclient\r"
expect "]#"
send "pip install python-ironicclient\r"
expect "]#"
send "source /etc/kolla/kolla-toolbox/admin-openrc.sh\r"
expect "]#"
close $spawn_id
